openapi: 3.0.0
info:
  title: Car Managment
  version: 1.0.0
servers:
  - url: https://car-management-108y.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/auth/signup:
    post:
      tags:
        - default
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: testuser
                password: password123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: testuser
                password: password123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cars:
    post:
      tags:
        - default
      summary: createCar
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: my new second car
                description:
                  type: string
                  example: This is a great car with amazing features.
                tags:
                  type: string
                  example: sedan, automatic , electric
                images:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: listCars
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cars/673833d20717d7a1630d8f9f:
    delete:
      tags:
        - default
      summary: deleteCar
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cars/67387959790bd88bb48cedfa:
    put:
      tags:
        - default
      summary: updateCar
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: BMW-S Class
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: SearchCar
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}